name: Build Image (Push Tag)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set variables
        run: |
          TAG=$(echo $GITHUB_REF | cut -d"/" -f3)
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "TAG=${TAG}"
          VERSION=${TAG#v}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}"
          echo "COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
          echo "COMMIT_SHA=${GITHUB_SHA}"
          #echo "REGISTRY_URL=XXXXXX.dkr.ecr.us-east-1.amazonaws.com" >> ${GITHUB_ENV}
          #echo "REGISTRY_URL=XXXXXX.dkr.ecr.us-east-1.amazonaws.com"
          echo "REGISTRY_URL=docker.io" >> ${GITHUB_ENV}
          echo "REGISTRY_URL=docker.io"
          echo "IMAGE_TAG=weniai/ipsec_exporter:${TAG}" >> ${GITHUB_ENV}
          echo "IMAGE_TAG=weniai/ipsec_exporter:${TAG}"
          echo "IMAGE_REPOSITORY=weni-ai/ipsec_exporter" >> ${GITHUB_ENV}
          echo "IMAGE_REPOSITORY=weni-ai/ipsec_exporter"

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{env.GITHUB_SHA}}
          repository: ${{env.IMAGE_REPOSITORY}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Login to ECR
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ${{env.REGISTRY_URL}}
      #    username: ${{secrets.AWS_ACCESS_KEY_ID_SHARED}}
      #    password: ${{secrets.AWS_SECRET_ACCESS_KEY_SHARED}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: branch=${{env.TAG}},commit=${{env.COMMIT_SHA}},repository=https://github.com/${{env.IMAGE_REPOSITORY}}
          file: Dockerfile
          push: true
          tags: ${{env.REGISTRY_URL}}/${{env.IMAGE_TAG}}
          no-cache: true

      - name: Generated Image
        run: |
          echo "IMAGE:      " ${{env.REGISTRY_URL}}/${{env.IMAGE_TAG}}

